# Generated by Django 3.0.6 on 2020-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full Time', max_length=100),
        ),
    ]
