# Generated by Django 3.0.6 on 2020-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20201223_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='representative_position',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logos'),
        ),
    ]
