# Generated by Django 3.0.6 on 2020-12-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_auto_20201226_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
