# Generated by Django 3.0.6 on 2021-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20201226_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Texas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
