# Generated by Django 3.1 on 2020-12-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
