# Generated by Django 3.1 on 2021-01-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_auto_20210107_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='noc_codes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='onet_codes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
