# Generated by Django 3.1 on 2020-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='California', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='3 years', max_length=100),
            preserve_default=False,
        ),
    ]
