# Generated by Django 3.0.6 on 2021-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_auto_20210112_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
