# Generated by Django 3.1 on 2020-12-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='pincode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='applicant',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
