# Generated by Django 3.1 on 2020-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20201225_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address_line1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/profile_pics'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='applicants/resumes'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
