# Generated by Django 3.0.6 on 2021-01-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_auto_20210107_2226'),
        ('applicant', '0004_auto_20201225_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applied_job', 'applicant')},
        ),
    ]
